name: update-yt-dlp

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-yt-dlp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Update yt-dlp
        run: |
          # 获取当前与线上最新版本号
          LATEST_VERSION=$(curl -s https://pypi.org/pypi/yt-dlp/json | jq -r '.info.version')
          CURRENT_VERSION=$(grep -oP '(?<=yt-dlp\[default,curl-cffi\]>=)[0-9.]+' pyproject.toml || echo "")

          echo "当前版本: $CURRENT_VERSION"
          echo "最新版本: $LATEST_VERSION"

          if [ -n "$LATEST_VERSION" ] && [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "发现新版本，正在更新 pyproject.toml..."
            sed -i -E "s/yt-dlp\[default,curl-cffi\]>=[0-9.]+/yt-dlp[default,curl-cffi]>=$LATEST_VERSION/g" pyproject.toml
            
            git config --global user.email "updater@twtube"
            git config --global user.name "AutoUpdater"
            git add pyproject.toml
            git commit -m "chore(deps): upgrade yt-dlp to $LATEST_VERSION"
            git push
          else
            echo "yt-dlp 已经是最新版本 ($CURRENT_VERSION)"
          fi